version: '3.8'
services:
  comfyui_launcher:
    image: thecooltechguy/comfyui_launcher
    container_name: comfyui_launcher
    ports:
      - "4000:4000"
    volumes:
      - ./comfyui_launcher_models:/app/server/models
      - ./comfyui_launcher_projects:/app/server/projects
    environment:
      - PROXY_MODE=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
